---
# ROLE: capistrano_setup
# roles/capistrano_setup/tasks/main.yml
#
# Sets up the capistrano deployment user and shared directories
# Usage:
#    - { role: capistrano_setup, project_name: YOUR_PROJECT_NAME }
# Optional:
# Declare a keys_to_add variable to copy github ssh keys
# to the deploy user
# vars:
#   keys_to_add:
#     - https://github.com/mark-dce.keys
#     - https://github.com/little9.keys
#     - https://github.com/no-reply.keys
#     - https://github.com/bess.keys

- name: create cap group
  become: yes
  group: name=deploy state=present

- name: create cap user
  become: yes
  user: name=deploy group=deploy shell=/bin/bash createhome=yes state=present

- name: create directories needed for capistrano
  become: yes
  file: path={{ item }} state=directory owner=deploy group=deploy
  with_items:
    - /opt/{{ project_name }}/shared/config
    - /opt/{{ project_name }}/shared/log
    - /opt/{{ project_name }}/shared/public/assets
    - /opt/{{ project_name }}/shared/tmp/pids
    - /opt/{{ project_name }}/releases
    - /opt/derivatives
    - /opt/uploads
    - /home/deploy/.ssh

- name: add keys for capistrano user
  become: yes
  authorized_key: user=deploy key={{ item }} exclusive=no state=present
  with_items:
    - "{{ keys_to_add }}"
  when: keys_to_add is defined and keys_to_add != None
