---
# ROLE: capistrano_setup
# roles/capistrano_setup/tasks/main.yml
#
# Sets up the capistrano deployment user and shared directories
# Usage:
#    - { role: capistrano_setup, project_name: YOUR_PROJECT_NAME }
# Optional:
# Declare a keys_to_add variable to copy github ssh keys
# to the deploy user
# vars:
#   keys_to_add:
#     - https://github.com/mark-dce.keys
#     - https://github.com/little9.keys
#     - https://github.com/no-reply.keys
#
# Optional:
# Declare a sudo_users variable to copy github ssh keys
# to the deploy user (useful for playbooks that include a sudo_users.yml file)
# vars:
#   sudo_users:
#.  - { username: 'mark', keys_to_add: 'https://github.com/mark-dce.keys' }
#   - { username: 'mml', keys_to_add: 'https://github.com/mlooney.keys' }


- name: create cap group
  become: yes
  group: name=deploy state=present

- name: create cap user
  become: yes
  user: name=deploy group=deploy shell=/bin/bash createhome=yes state=present

- name: add keys for capistrano user from keys_to_add array
  become: yes
  authorized_key: user=deploy key={{ item }} exclusive=no state=present
  with_items:
    - "{{ keys_to_add }}"
  when: keys_to_add is defined and keys_to_add != None

- name: add keys for capistrano user from sudo_users array
  become: yes
  authorized_key: user=deploy key={{ item.keys_to_add }} exclusive=no state=present
  with_items:
    - "{{ sudo_users }}"
  when: sudo_users is defined and sudo_users != None

- name: add shell for capistrano user
  become: yes
  cron:
    user: deploy
    name: SHELL
    env: yes
    value: /bin/sh

# Creates an entry like "PATH=/opt/bin" on top of crontab
- name: add crontab path for capistrano user
  become: yes
  cron:
    user: deploy
    name: PATH
    env: yes
    value: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    insertafter: SHELL

- name: allow deploy user to restart apache2
  become: yes
  template: src=apache2.deploy.sudoers.j2 dest=/etc/sudoers.d/apache2-deploy-restart owner=root group=root backup=no

- name: add www-data user to deploy group
  become: yes
  user:
    name: www-data
    groups: deploy
    append: yes

