---
# ROLE: setup_logrotation
# roles/setup_logrotation/tasks/main.yml

# Sets up logrotation
# Usage:
#    - { role: setup_logrotation, syslog_keep_days: 7, utility_log_keep_weeks: 4 }
# the above example keeps system logs for 7 days and utility logs for 4 weeks

- name: set rotation for system logs
  become: yes
  template: src=logrotate-sys.j2 dest=/etc/logrotate.d/rsyslog backup=yes

- name: set up journald config dir
  become: yes
  file:
    path: /etc/systemd/journald.conf.d
    state: directory

- name: set up journald disk usage
  become: yes
  template: src=diskusage.conf dest=/etc/systemd/journald.conf.d/00diskusage.conf owner=root group=root
  notify: restart journald
