# ROLE: fits
# roles/fits/tasks/main.yml
#
# Installs FITS (File Information Tool Set) both as a standalone toolkit and as a servlet.
# Usage:
#    - { role: fits, fits_version: '1.4.0', fits_servlet_version: '1.2.0' }
# Note that if you don't specify the fits_servlet_version the last step might fail for unknown reasons.

- name: ensure fits_version is set
  set_fact:
    fits_version: '1.5.1'
  when: fits_version is not defined

- name: ensure fits_servlet_version is set
  set_fact:
    fits_servlet_version: '1.2.3'
  when: fits_servlet_version is not defined

# Install FITS command line tool
- name: make fits version folder
  become: yes
  file:
    state: directory
    path:  /usr/local/lib/fits-{{ fits_version }}

- name: download and unzip fits {{ fits_version }} source
  become: yes
  ansible.builtin.unarchive:
    src: https://github.com/harvard-lts/fits/releases/download/{{ fits_version }}/fits-{{ fits_version }}.zip
    dest: /usr/local/lib/fits-{{ fits_version }}
    creates: /usr/local/lib/fits-{{ fits_version }}/fits.sh
    remote_src: yes

- name: only send logging to console
  become: yes
  lineinfile:
    # Syslog or catalina will capture output, so we want to remove the FILE logger
    # was 'log4j.rootLogger=INFO, CONSOLE, FILE'
    line: 'log4j.rootLogger=INFO, CONSOLE'
    dest: /usr/local/lib/fits-{{ fits_version }}/log4j.properties
    regexp: 'log4j.rootLogger='

- name: make fits executable
  become: yes
  file: 
    path: /usr/local/lib/fits-{{ fits_version }}/fits.sh
    mode: 0755

- name: symlink fits alias
  become: yes
  file: src=/usr/local/lib/fits-{{ fits_version }}/fits.sh dest=/usr/local/bin/fits state=link

- name: symlink fits.sh alias
  become: yes
  file: src=/usr/local/lib/fits-{{ fits_version }}/fits.sh dest=/usr/local/bin/fits.sh state=link

# Install and configure FITS servlet
- name: look up service names
  become: yes
  ansible.builtin.service_facts:

- name: set tomcat service name
  set_fact:
    tomcat_service: "{{ ansible_facts.services.keys() | regex_search('tomcat[0-9]+') }}" 

- name: set shared libs in catalina.properties
  become: yes
  lineinfile: dest=/etc/{{ tomcat_service }}/catalina.properties regexp="^shared.loader=" line="shared.loader=\"/usr/local/lib/fits-{{ fits_version }}/lib/*.jar\"" state=present
  when: fits_version is match("^0\.([8-9]|10)\.[0-9]|1\.[0-9]\.[0-9]")

- name: set defaults into tomcat
  become: yes
  lineinfile:
    dest: /etc/default/{{ tomcat_service }}
    line: "JAVA_OPTS=\"${JAVA_OPTS} -Dfits.home=/usr/local/lib/fits-{{ fits_version }}\""
    insertafter: EOF

- name: download fits servlet version {{ fits_servlet_version }}
  become: yes
  get_url:
    url: https://github.com/harvard-lts/FITSservlet/releases/download/{{ fits_servlet_version }}/fits-service-{{ fits_servlet_version }}.war
    owner: tomcat
    group: tomcat
    dest: /var/lib/{{ tomcat_service }}/webapps/fits-{{ fits_servlet_version }}.war
    checksum: md5:https://github.com/harvard-lts/FITSservlet/releases/download/1.2.3/fits-service-1.2.3.war.md5
    force: yes

- name: restart servlet
  become: yes
  service: name={{ tomcat_service }} enabled=yes state=restarted

- name: check that fits-servlet is up
  uri:
    url: 'http://localhost:8080/fits-{{ fits_servlet_version}}/'
    timeout: 180
    return_content: yes
  register: webpage

- fail: msg='FITS server is not running as expected'
  when: "'FITS Web Service' not in webpage.content"
