---
# ROLE: set_hostname
# roles/set_hostname/tasks/main.yml

# Sets the server hostname.
# This role will fail if you call it
# without hostname and domain being set.
# Usage:
#    - { role: set_hostname, hostname: 'my_server', domain: 'example.com' }

- name: Set hostname
  become: yes
  hostname: name={{ [hostname, domain] | join('.') }}

- name: Edit /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    state: present
    line: 127.0.0.1 {{ hostname }} {{ [hostname, domain] | join('.') }}
