---
# ROLE: fedora
# roles/fedora/tasks/main.yml
#
# To back fedora with postgres, set these variables:
# fedora_database: jdbc-postgresql
# You must also create a postgres database called `fcrepo` and give the "tomcat" user
# rights on it

- name: setup install directory
  set_fact:
    install_path: /home/{{ ansible_ssh_user }}/install

- name: ensure install directory exists
  file:
    path: '{{ install_path }}'
    state: directory

- name: install servlet container package
  become: yes
  package: name=tomcat9 state=present

- name: download fedora
  get_url: url=https://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/{{ fedora_version }}/fcrepo-webapp-{{ fedora_version }}.war owner={{ ansible_ssh_user }} dest={{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war timeout=100

- name: make fedora data dir
  file: owner=tomcat group=tomcat state=directory path=/opt/fedora-data
  become: yes

- name: check fedora.war
  stat: path=/var/lib/tomcat9/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  become: yes
  command: cp {{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war /var/lib/tomcat9/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: install activation
  become: yes
  get_url: url=https://repo1.maven.org/maven2/javax/xml/bind/activation/1.0.2/activation-1.0.2.jar owner=tomcat dest=/var/lib/tomcat9/lib/activation-1.0.2.jar timeout=100

- name: install jaxb
  become: yes
  get_url: url=https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar owner=tomcat dest=/var/lib/tomcat9/lib/jaxb-api-2.3.1.jar timeout=100

- name: create service override directory
  become: yes
  file: 
    path: /etc/systemd/system/tomcat9.service.d
    state: directory

- name: create systemd configuration
  become: yes
  template: src=tomcat9.service dest=/etc/systemd/system/tomcat9.service.d/override.conf

- name: set port for tomcat
  become: yes
  replace:
    dest: /etc/tomcat9/server.xml
    regexp: "8080"
    replace: "{{ tomcat_port }}"

- name: add log rotation for catalina.out (tomcat/fedora logs)
  become: yes
  template: src=logrotate-tomcat dest=/etc/logrotate.d/tomcat9 backup=yes

- name: restart servlet
  become: yes
  systemd: name=tomcat9 state=restarted daemon_reload=yes
