---
# ROLE: fedora
# roles/fedora/tasks/main.yml
#
# To back fedora with postgres, set these variables:
# fedora_database: jdbc-postgresql
# fcdb_user: fcdb_user
# fcdb_pass: whatever
# You must also create a postgres database called `fcrepo` and give the fcdb_user
# rights on it
# Note that backing fedora with PostGres is our default and is ALWAYS how we want
# to run things in production.

- name: create fcrepo database
  postgresql_db: name=fcrepo state=present login_user=postgres
  become: yes
  become_user: postgres

- name: add samvera user
  postgresql_user: db=fcrepo name={{ fcdb_user }} password={{ fcdb_pass }} priv=ALL state=present login_user=postgres
  become: yes
  become_user: postgres

- name: setup install directory
  set_fact:
    install_path: /home/{{ ansible_ssh_user }}/install

- name: ensure install directory exists
  file:
    path: '{{ install_path }}'
    state: directory

- name: install servlet container package
  become: yes
  package: name=tomcat9 state=present

- name: download fedora
  get_url: url=https://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/{{ fedora_version }}/fcrepo-webapp-{{ fedora_version }}.war owner={{ ansible_ssh_user }} dest={{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war timeout=100

- name: make fedora data dir
  file: owner=tomcat group=tomcat state=directory path=/opt/fedora-data
  become: yes

- name: check fedora.war
  stat: path=/var/lib/tomcat9/webapps/fedora.war
  register: fedora_war

- name: copy over fedora.war
  become: yes
  command: cp {{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war /var/lib/tomcat9/webapps/fedora.war
  when: fedora_war.stat.exists == False

- name: install activation
  become: yes
  get_url: url=https://repo1.maven.org/maven2/javax/xml/bind/activation/1.0.2/activation-1.0.2.jar owner=tomcat dest=/var/lib/tomcat9/lib/activation-1.0.2.jar timeout=100

- name: install jaxb
  become: yes
  get_url: url=https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar owner=tomcat dest=/var/lib/tomcat9/lib/jaxb-api-2.3.1.jar timeout=100

- name: create systemd configuration
  become: yes
  template: src=tomcat9.service dest=/lib/systemd/system/tomcat9.service backup=yes

- name: create tomcat config and java options
  become: yes
  template:
    src: tomcat9.j2
    dest: "{{ fedora_config_file }}"
    owner: tomcat
    group: tomcat
    backup: yes

- name: set port for tomcat
  become: yes
  replace:
    dest: /etc/tomcat9/server.xml
    regexp: "8080"
    replace: "{{ tomcat_port }}"

- name: add log rotation for catalina.out (tomcat/fedora logs)
  become: yes
  template: src=logrotate-tomcat dest=/etc/logrotate.d/tomcat9 backup=yes

- name: restart servlet
  become: yes
  systemd: name=tomcat9 state=restarted daemon_reload=yes
