---
# ROLE: fedora
# roles/fedora/tasks/main.yml
#
# To back fedora with postgres, set these variables:
# fedora_database: jdbc-postgresql
# You must also create a postgres database called `fcrepo` and give the "tomcat" user
# rights on it

- name: make fedora data dir
  become: yes
  file:
    owner: tomcat
    group: tomcat
    state: directory
    path:  /opt/fedora-data

- name: add fedora settings to tomcat defaults
  become: true
  blockinfile:
    path: /etc/default/tomcat9
    block: |
      JAVA_OPTS="${JAVA_OPTS} -Dfcrepo.modeshape.configuration=classpath:/config/jdbc-postgresql/repository.json"
      JAVA_OPTS="${JAVA_OPTS} -Dfcrepo.home=/opt/fedora-data"
      JAVA_OPTS="${JAVA_OPTS} -Dfcrepo.postgresql.username=tomcat"
      JAVA_OPTS="${JAVA_OPTS} -Dfcrepo.postgresql.port=5432"

- name: download fedora war & instal in tomcat
  become: yes
  get_url:
    url: https://repo1.maven.org/maven2/org/fcrepo/fcrepo-webapp/{{ fedora_version }}/fcrepo-webapp-{{ fedora_version }}.war 
    dest: '/var/lib/tomcat9/webapps/fedora.war'
    timeout: 100

- name: install activation
  become: yes
  get_url:
    url: https://repo1.maven.org/maven2/javax/xml/bind/activation/1.0.2/activation-1.0.2.jar
    owner: tomcat
    dest: /var/lib/tomcat9/lib/activation-1.0.2.jar
    timeout: 100

- name: install jaxb
  become: yes
  get_url:
    url: https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar
    owner: tomcat
    dest: /var/lib/tomcat9/lib/jaxb-api-2.3.1.jar
    timeout: 100

- name: create service override directory
  become: yes
  file: 
    path: /etc/systemd/system/tomcat9.service.d
    state: directory

- name: create systemd configuration additions for fedora
  become: yes
  copy:
    dest: /etc/systemd/system/tomcat9.service.d/fedora.conf
    content: |
      [Service]
      ReadWritePaths=/opt/fedora-data
      ReadWritePaths=/tmp

- name: restart servlet
  become: yes
  systemd: name=tomcat9 state=restarted daemon_reload=yes

- name: check fedora web gui
  uri:
    url: http://localhost:8080/fedora/rest
    return_content: yes
  register: webpage

- fail: msg='fedora is not running as expected'
  when: "'fedora:Resource' not in webpage.content"
