# Output vhost and error logs in JSON format
LogFormat "{ \"time\":\"%{%Y-%m-%dT%H:%M:%S}t.%{usec_frac}t%{%z}t\", \"microseconds\":%D, \"request_id\":\"%{UNIQUE_ID}e\", \"filename\":\"%f\", \"remoteIP\":\"%a\", \"host\":\"%V\", \"port\":%p, \"protocol\":\"%H\", \"request\":\"%U\", \"query\":\"%q\",\"method\":\"%m\", \"status\":\"%>s\", \"userAgent\":\"%{User-agent}i\",\"referer\":\"%{Referer}i\", \"error_id\":\"%L\", \"bytes\":{\"in\": %I, \"out\": %O} }\n" json
ErrorLogFormat "{\"time\":\"%{cu}tZ\", \"logi_id\":\"%L\", \"function\" : \"[%-m:%l]\", \"process\" : \"[pid%P]\" ,\"message\" : \"%M\"}\n"

CustomLog ${APACHE_LOG_DIR}/other_vhosts_access.log json

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
