- name: Ensure backup script directory exists
  become: yes
  file:
    path: /opt/pg_backups/pg_daily_double
    state: directory

- name: add pg_backups script
  become: yes
  template: src=pg_backups.j2 dest=/opt/pg_backups/pg_daily_double owner=root group=root mode=0755
  tags:
    - postgres
    - configure

- name: add pg_backups cron job
  become: yes
  cron: name="backup pg db" user=postgres job="/opt/pg_backups/pg_daily_double" minute="0" hour="1" state=present
  tags:
    - postgres
    - configure


- name: add samvera application user
  become: yes
  become_user: postgres
  postgresql_user: name=deploy role_attr_flags=SUPERUSER
  tags:
    - postgres
    - configure

- name: add fedora application user
  become: yes
  become_user: postgres
  postgresql_user: name=tomcat role_attr_flags=SUPERUSER
  tags:
    - postgres
    - configure

- name: create samvera database
  become: yes
  become_user: postgres
  postgresql_db: name={{ project_name }} state=present login_user=postgres owner=deploy
  tags:
    - postgres
    - configure

- name: configure Fedora
  when: configure_fedora == True
  block: 
  - name: create fcrepo database
    postgresql_db: name=fcrepo state=present login_user=postgres owner=tomcat
    become: yes
    become_user: postgres
    tags:
      - postgres
      - fedora
      - configure

  - name: create Fedora config and java options
    become: yes
    template:
      src: tomcat9.j2
      dest: "{{ fedora_config_file }}"
      owner: tomcat
      group: tomcat
      backup: yes
    tags:
      - fedora
      - configure

  - name: restart Fedora servlet
    become: yes
    systemd: name=tomcat9 state=restarted daemon_reload=yes
    tags:
      - fedora
      - configure
  # block end - configure Fedora

- name: create default solr collection
  become: yes
  become_user: solr
  shell: /opt/solr/bin/solr create -c {{ project_name }} -d _default -p {{ solr_port }} creates=/var/solr/data/{{ project_name }}
  tags:
    - solr
    - configure

- name: create directories needed for capistrano
  become: yes
  file: path={{ item }} state=directory owner=deploy group=deploy
  with_items:
    - /opt/{{ project_name }}/shared/config
    - /opt/{{ project_name }}/shared/log
    - /opt/{{ project_name }}/shared/public/assets
    - /opt/{{ project_name }}/shared/tmp/pids
    - /opt/{{ project_name }}/releases
    - /opt/derivatives
    - /opt/uploads
    - /opt/data
    - /home/deploy/.ssh
  tags:
    - capistrano
    - configure

- name: configure Cantaloupe
  when: configure_cantaloupe == True
  block:
  - name: write cantaloupe config file
    become: yes
    template:
      src: ansible-samvera/roles/cantaloupe/templates/cantaloupe.properties
      dest: /opt/cantaloupe-{{ cantaloupe_version }}/cantaloupe.properties
      owner: cantaloupe
      group: cantaloupe
      mode: 0644
    tags:
      - cantaloupe
      - configure

  - name: (re)start cantaloupe
    become: yes
    shell: systemctl restart cantaloupe.service
    tags:
      - cantaloupe
      - configure
  # end block - configure Cantaloupe

