# ROLE: restart
# roles/restart/tasks/main.yml
#
# Restarts essential services
# Intended to be used after installing packages
# at the end of the playbook
# Usage:
#    - { role: restart }

- name: restart solr
  become: yes
  service:
    name: solr
    state: restarted

- name: restart fedora
  become: yes
  service:
    name: tomcat8
    enabled: yes
    state: restarted

- name: restart apache
  become: yes
  service:
    name: apache2
    enabled: yes
    state: restarted
