# ROLE: restart
# roles/restart/tasks/main.yml
#
# Restarts essential services
# Intended to be used after installing packages
# at the end of the playbook
# Usage:
#    - { role: restart }

- name: restart solr
  become: yes
  service:
    name: solr
    state: restarted

- name: restart fedora
  become: yes
  service:
    name: tomcat9
    enabled: yes
    state: restarted

- name: restart apache
  become: yes
  service:
    name: apache2
    enabled: yes
    state: restarted

- name: restart clamav
  become: yes
  service:
    name: clamav-daemon
    enabled: yes
    state: restarted

- name: restart freshclam
  become: yes
  service:
    name: clamav-freshclam
    enabled: yes
    state: restarted


# not everything has cantaloupe. this is an ansible+ubuntu 2.9 bug resolved in 2.10
# so we can't conditionally restart yet.
#- name: get service facts
#  service_facts:
#- name: restart cantaloupe
#  become: yes
#  service:
#    name: cantaloupe
#    enabled: yes
#    state: restarted
#  when: "'cantaloupe.service' in services"
