- name: add Yarn apt repository
  become: yes
  deb822_repository:
    name: yarn
    types: deb
    uris: https://dl.yarnpkg.com/debian/
    suites: stable
    components: main
    signed_by: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: update and install yarn
  become: true
  apt:
    name: yarn
    update_cache: true
