---
# ROLE: tomcat9
# roles/tomcat9/tasks/main.yml
#
# installs tomcat9 for Ubuntu LTS 24.04

# NOTE: FITS and Fedora reuqire Tomcat9 (Java EE) and are not compatible with Tomcat10 (Jakarta EE)
# Ubuntu LTS 24.04 (Noble) only includes Tomcat10 in apt repostiories, so we are installing the
# Tomcat9 packages from the LTS 22.04 (Jammy) repositories

- name: install libtomcat9-java
  become: yes
  ansible.builtin.apt:
    deb: http://launchpadlibrarian.net/786086833/libtomcat9-java_9.0.58-1ubuntu0.2_all.deb

- name: install tomcat9-common
  become: yes
  ansible.builtin.apt:
    deb: http://launchpadlibrarian.net/786086835/tomcat9-common_9.0.58-1ubuntu0.2_all.deb

- name: install tomcat9
  become: yes
  ansible.builtin.apt:
    deb: http://launchpadlibrarian.net/786086840/tomcat9_9.0.58-1ubuntu0.2_all.deb

- name: install tomcat9-admin
  become: yes
  ansible.builtin.apt:
    deb: http://launchpadlibrarian.net/786086834/tomcat9-admin_9.0.58-1ubuntu0.2_all.deb

- name: configure tomcat9 admin user
  become: yes
  lineinfile:
    dest: /var/lib/tomcat9/conf/tomcat-users.xml
    state: present
    line: <role rolename="manager-gui"/><user username="rdb-manager" password="{{ tomcat_web_gui_password }}" roles="manager-gui"/>
    insertbefore: </tomcat-users>

- name: customize tomcat default settings
  become: true
  blockinfile:
    path: /etc/default/tomcat9
    insertafter: EOF
    block: |
      # Customized settings for Hyrax environments
      JAVA_OPTS="${JAVA_OPTS} -Dlog4j2.formatMsgNoLookups=true"
      JAVA_OPTS="${JAVA_OPTS} -Djava.awt.headless=true"
      JAVA_OPTS="${JAVA_OPTS} -XX:+UseG1GC"
      JAVA_OPTS="${JAVA_OPTS} -XX:+UseCompressedOops"
      JAVA_OPTS="${JAVA_OPTS} -XX:-UseLargePagesIndividualAllocation"
      JAVA_OPTS="${JAVA_OPTS} -Xms{{ tomcat_min_memory | default('1024m') }}"
      JAVA_OPTS="${JAVA_OPTS} -Xmx{{ tomcat_max_memory | default('2048m') }}"
      JAVA_OPTS="${JAVA_OPTS} -Djava.util.logging.config.file=/etc/tomcat9/logging.properties"
      JAVA_OPTS="${JAVA_OPTS} -server"

- name: restart tomcat9
  become: yes
  service:
    name: tomcat9
    enabled: yes
    state: restarted
    
- name: check tomcat web gui
  uri:
    url: http://localhost:8080/manager/html
    user: rdb-manager
    password: "{{ tomcat_web_gui_password }}"
    force_basic_auth: yes
    return_content: yes
  register: webpage

- fail: msg='tomcat9 is not running as expected'
  when: "'Tomcat Web Application Manager' not in webpage.content"
