---
- name: remove package ghostscript
  become: yes
  package: name=ghostscript state=absent

- name: download and unzip ghostscript source
  ansible.builtin.unarchive:
    src: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs{{ gs_ver | regex_replace("\.","")}}/ghostscript-{{ gs_ver }}.tar.xz
    dest: imagemagick_sources
    creates: imagemagick_sources/ghostscript-{{ gs_ver }}
    remote_src: yes

- name: configure ghostscript
  shell:
    cmd: ./configure
    chdir: imagemagick_sources/ghostscript-{{ gs_ver }}
    creates: ./config.status

- name: make ghostscript
  shell:
    cmd: make
    chdir: imagemagick_sources/ghostscript-{{ gs_ver }}
    creates: ./bin/gs

- name: install ghostscript
  become: yes
  shell:
    cmd: make install
    chdir: imagemagick_sources/ghostscript-{{ gs_ver }}
    creates: /usr/local/bin/gs
