---
- name: download and unzip libpng source
  ansible.builtin.unarchive:
    src: https://download.sourceforge.net/libpng/libpng-{{ libpng_ver }}.tar.xz
    dest: imagemagick_sources
    creates: imagemagick_sources/libpng-{{ libpng_ver }}
    remote_src: yes

- name: configure libpng
  shell:
    cmd: ./configure
    chdir: imagemagick_sources/libpng-{{ libpng_ver }}

- name: make libpng
  shell:
    cmd: make
    chdir: imagemagick_sources/libpng-{{ libpng_ver }}

- name: install libpng
  become: yes
  shell:
    cmd: make install
    chdir: imagemagick_sources/libpng-{{ libpng_ver }}
