---
- name: download libtiff source
  get_url:
    url: https://download.osgeo.org/libtiff/tiff-{{ libtiff_ver }}.tar.gz
    dest: "imagemagick_sources/tiff-{{ libtiff_ver }}.tar.gz"
    force: no

- name: unzip libtiff source
  shell: tar zxvf tiff-{{ libtiff_ver }}.tar.gz creates=tiff-{{ libtiff_ver }} warn=no
  args:
    chdir: imagemagick_sources

- name: configure libtiff
  shell: ./configure
  args:
    chdir: imagemagick_sources/tiff-{{ libtiff_ver }}

- name: make libtiff
  shell: make
  args:
    chdir: imagemagick_sources/tiff-{{ libtiff_ver }}

- name: install libtiff
  become: yes
  shell: make install
  args:
    chdir: imagemagick_sources/tiff-{{ libtiff_ver }}
