---
- name: fetch and unzip libtiff source
  ansible.builtin.unarchive:
    src: https://download.osgeo.org/libtiff/tiff-{{ libtiff_ver }}.tar.gz
    dest: imagemagick_sources
    creates: imagemagick_sources/tiff-{{ libtiff_ver }}
    remote_src: yes

- name: configure libtiff
  shell:
    cmd: ./configure
    chdir: imagemagick_sources/tiff-{{ libtiff_ver }}

- name: make libtiff
  shell:
    cmd: make
    chdir: imagemagick_sources/tiff-{{ libtiff_ver }}

- name: install libtiff
  become: yes
  shell:
    cmd: make install
    chdir: imagemagick_sources/tiff-{{ libtiff_ver }}
