---
# ROLE: solr
# roles/solr/tasks/main.yml
#
# installs solr in production mode
#

- name: setup install directory
  set_fact:
    install_path: /home/{{ ansible_ssh_user }}/install

- name: ensure install directory exists
  file:
    path: '{{ install_path }}'
    state: directory

- name: download solr checksum
  become: yes
  get_url: url=https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz.sha512 dest={{ install_path }}/solr-{{ solr_version }}.tgz.sha512 force=no

- name: read solr checksum
  become: yes
  shell: awk '{print $1}' {{ install_path }}/solr-{{ solr_version }}.tgz.sha512
  register: solr_sha512

- name: download solr tarball
  become: yes
  get_url: url=https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/solr-{{ solr_version }}.tgz force=no checksum="sha512:{{ solr_sha512.stdout }}"

- name: untar solr tarball
  become: yes
  unarchive: src={{ install_path }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/ creates={{ install_path }}/solr-{{ solr_version }}/bin/solr copy=no

- name: check if standalone solr is installed
  stat: path=/etc/default/solr.in.sh
  register: solr_init_script

- name: run standalone solr service install script
  become: yes
  shell: bash {{ install_path }}/solr-{{ solr_version }}/bin/install_solr_service.sh {{ install_path }}/solr-{{ solr_version }}.tgz -p {{ solr_port }}
  when: solr_init_script.stat.exists == False

- name: configure solr loggers
  become: yes
  become_user: solr
  copy:
    src: log4j.properties
    dest: /var/solr/log4j.properties
    mode: 0640

- name: put in place Solr limits.d configuration
  become: yes
  copy:
    src: solr_limits.conf
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: 0644

# See https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu
- name: Increase max open files in user.conf
  become: yes
  lineinfile:
    path: /etc/systemd/user.conf
    state: present
    regexp: DefaultLimitNOFILE
    line: DefaultLimitNOFILE=65535

# See https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu
- name: Increase max processes in user.conf
  become: yes
  lineinfile:
    path: /etc/systemd/user.conf
    state: present
    regexp: DefaultLimitNPROC
    line: DefaultLimitNPROC=65535

# See https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu
- name: Increase max open files in system.conf
  become: yes
  lineinfile:
    path: /etc/systemd/system.conf
    state: present
    regexp: DefaultLimitNOFILE
    line: DefaultLimitNOFILE=65535

# See https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu
- name: Increase max processes in system.conf
  become: yes
  lineinfile:
    path: /etc/systemd/system.conf
    state: present
    regexp: DefaultLimitNPROC
    line: DefaultLimitNPROC=65535

- name: "template solr variable configuration"
  become: yes
  template: src=solr.in.sh.j2 dest=/etc/default/solr.in.sh owner=root group=solr

- name: enable solr system service
  become: yes
  systemd:
    name: solr
    enabled: yes

- name: restart solr system service
  become: yes
  systemd:
    name: solr
    state: restarted

- name: symlink solr logs to /var/log
  become: yes
  file:
    src: "/var/solr/logs"
    dest: "/var/log/solr"
    state: link
