---
# ROLE: solr
# roles/solr/tasks/main.yml
#
# installs solr in production mode
#

- name: setup install directory
  set_fact:
    install_path: /home/{{ ansible_ssh_user }}/install

- name: ensure install directory exists
  file:
    path: '{{ install_path }}'
    state: directory

- name: download solr checksum
  become: yes
  get_url: url=http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz.md5 dest={{ install_path }}/solr-{{ solr_version }}.tgz.md5 force=no

- name: read solr checksum
  become: yes
  shell: awk '{print $1}' {{ install_path }}/solr-{{ solr_version }}.tgz.md5
  register: solr_md5

- name: download solr tarball
  become: yes
  get_url: url=http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/solr-{{ solr_version }}.tgz force=no checksum="md5:{{ solr_md5.stdout }}"

- name: untar solr tarball
  become: yes
  unarchive: src={{ install_path }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/ creates={{ install_path }}/solr-{{ solr_version }}/bin/solr copy=no

- name: check if standalone solr is installed
  stat: path=/etc/default/solr.in.sh
  register: solr_init_script

- name: run standalone solr service install script
  become: yes
  shell: bash {{ install_path }}/solr-{{ solr_version }}/bin/install_solr_service.sh {{ install_path }}/solr-{{ solr_version }}.tgz -p {{ solr_port }}
  when: solr_init_script.stat.exists == False

- name: remove managed schema
  become: yes
  file:
    path: /var/solr/data/{{ project_name }}/conf/managed_schema
    state: absent

- name: create default collection
  become: yes
  become_user: solr
  shell: /opt/solr/bin/solr create -c {{ project_name }} -d basic_configs -p {{ solr_port }} creates=/var/solr/data/{{ project_name }}

- name: Set JVM heap size
  become: yes
  lineinfile:
    path: /etc/default/solr.in.sh
    state: present
    regexp: '^#SOLR_JAVA_MEM|^SOLR_JAVA_MEM'
    line: SOLR_JAVA_MEM="-Xms{{ solr_min_mem }}m -Xmx{{ solr_max_mem }}m"

- name: restart solr service
  become: yes
  service:
    name: solr
    state: restarted
